version: 2.1

# Prerequisite
# Make sure you set secret enviroment variables in CICD
# DOCKER_USERNAME
# DOCKER_PASSWORD
# API_TOKEN

# REBUILD - it has default value "false", if need rebuild the image, turn it on with value "true"

parameters:
  rebuild:
    type: string
    default: "false"

jobs:
  build:
    docker:
      - image: alpine/docker-with-buildx
    environment:
      REBUILD: << pipeline.parameters.rebuild >>
      APPLICATIONS: links lynx mysql psql curl semver
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run: |
          apk --no-cache --update add bash curl jq
          echo $REBUILD
          for app in ${APPLICATIONS}
          do
            bash ./build.sh ${app} 
          done

          # trivy doesn't support all platforms
          bash ./build_trivy.sh

  scan:
    docker:
      - image: alpine/trivy
    environment:
      APPLICATIONS: links lynx mysql psql curl trivy semver
    steps:
      - checkout
      - run: |
          for app in ${APPLICATIONS}
          do
            echo "Scan image alpine/${app} ..."
            trivy image -s "HIGH,CRITICAL" alpine/${app}
            echo "==== End of Scan ===="
          done

workflows:
  build:
    jobs:
      - build:
          name: build
          context:
            - Docker-Hub
          filters:
            branches:
              only:
                - master
                - main
      - scan:
          requires:
            - build
          name: scan
          context:
            - Docker-Hub
          filters:
            branches:
              only:
                - master
                - main

  nightly:
    triggers:
       - schedule:
           cron: "0 3 * * 0"
           filters:
             branches:
               only:
                 - master
                 - main
    jobs:
      - build:
          name: build
          context:
            - Docker-Hub
          filters:
            branches:
              only:
                - master
                - main

      - scan:
          requires:
            - build
          name: scan
          context:
            - Docker-Hub
          filters:
            branches:
              only:
                - master
                - main
